---
#Name:Role for creating Infrastructure (VPC, Subnet, IGW,Route tables,security group,EC2 Keypair,EC2 instance,ELB) on AWS.
#
# Current Author: Bunty Manchundiya.
#
# Created: 03-10-2018


- name: Create EC2 server
  ec2:
    image: ami-01e3b8c3a51e88954
    wait: yes
    instance_type: t2.micro
    region: "{{ region }}"
    group_id: "sg-0b62197adedc81664"
    instance_tags:
        Name: Ansible_instance
    count_tag:
      Name: apacheserver
    exact_count: 1
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2_id
- set_fact:
   var1: "{{ec2_id.instance_ids[0]}}"





