---

- name: Create EC2 server
  ec2:
    image: ami-049ceee18ac22d417
    wait: yes
    instance_type: t2.micro
    region: "{{ region }}"
    group_id: "sg-09bad65848196207d"
    instance_tags:
        Name: Ansible_instance2
    count_tag:
      Name: apacheserver
    exact_count: 1
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2_id
- set_fact:
   var1: "{{ec2_id.instance_ids[0]}}"





